### PR TITLE
added breaking vue sfc tests

### PR DESCRIPTION
**Pull request by suterma**
### Which issue does this PR address?

Addresses #4 by adding some failing Vue Js SFC tests.
I also have changed some minor stuff like mocha running in watch mode.

Feel free to pick anything or nothing from this PR.

As a side-note: I still guess, as mentioned earlier, that extending your plugin for non-js code would probably require quite a change. I am happily using it as-is, with only enabling it for the JS part. Thanks for your effort with this plugin anyway.

### CODE REVIEW

**Comment by nikku** [comment]
Cf. https://github.com/nikku/eslint-plugin-license-header/pull/16 for a working vue test.

Next step would be what the desired "check for license" location in a vue file would be. How would it deal with `<script />` last in the template? Would the license always be attached to _script_? Or would the plug-in goal be to simply ignore vue files?

**Comment by suterma** [comment]
The [Vue SFC spec](https://vuejs.org/api/sfc-spec) states that there may be an arbitrary amount of code blocks, each living inside angle brackets. In fact you can thing of it like a partial HTML file, only having the content from the body tag.

I have placed the comment in my files as HTML comments on the top of my files, e.g. in https://github.com/suterma/replayer-pwa/blob/main/src/App.vue, as I consider the text part in question some form of header (as is in the name of this plugin).

**Comment by nikku** [comment]
So then the right way to pursue non JS components is to completely ignore them from matching / fixing. Another checker shall do the job for them.

**Comment by nikku** [comment]
Closed in favor of https://github.com/nikku/eslint-plugin-license-header/pull/16.

**Pull request closed without merging**
